package oficinacomercial;

import Clases.Persona;
import Clases.Vuelo;
import comunicacion.ClienteConexion;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.Vector;
import javax.swing.JOptionPane;

/**
 * @author Angelica Omaña
 * @author Mary Carrascal
 * @author Luis Figueras
 * @author Emmanuel Ortiz
 * @author Juan Escalante
 * @author Gustavo Briceño
 */

public class GUI extends javax.swing.JFrame {

    Vector respuesta = new Vector();
    /** Creates new form interfaz */
    public GUI() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cmbOrigen = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        cmbDestino = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        regreso = new javax.swing.JLabel();
        idaVuelta = new javax.swing.JRadioButton();
        ida = new javax.swing.JRadioButton();
        calendarioSalida = new org.freixas.jcalendar.JCalendarCombo();
        calendarioRegreso = new org.freixas.jcalendar.JCalendarCombo();
        consultarVuelos = new javax.swing.JButton();
        solicitar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtCedulaPagar = new javax.swing.JTextField();
        comprarReserva = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        txtcedulaModificar = new javax.swing.JTextField();
        buscar_Modificar = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        modificarDatos = new javax.swing.JButton();
        txtNombre = new javax.swing.JTextField();
        txtApellido = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        txtCiudad = new javax.swing.JTextField();
        txtEstado = new javax.swing.JTextField();
        txtZona = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        txtCedulaElim = new javax.swing.JTextField();
        Buscar_Eliminar = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtOrigenVuelo = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtDestinoVuelo = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        txtFechaSalidaVuelo = new javax.swing.JTextField();
        EliminarCompraVuelo = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        txtFechaRegreso = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        txtNumeroVuelo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.setFont(new java.awt.Font("Tahoma", 1, 11));

        jLabel1.setText("Eliga el Origen");

        cmbOrigen.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Caracas", "Maracaibo", "Valencia", "Barinas", "Merida", "Puerto La Cruz", "Barcelona", "Cumana", " " }));
        cmbOrigen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbOrigenActionPerformed(evt);
            }
        });

        jLabel2.setText("Eliga el Destino");

        cmbDestino.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " " }));

        jLabel3.setText("Fecha de Salida");

        regreso.setText("Fecha de Regreso");

        buttonGroup1.add(idaVuelta);
        idaVuelta.setFont(new java.awt.Font("Tahoma", 1, 11));
        idaVuelta.setText("Ida y Vuelta");
        idaVuelta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idaVueltaActionPerformed(evt);
            }
        });

        buttonGroup1.add(ida);
        ida.setFont(new java.awt.Font("Tahoma", 1, 11));
        ida.setText("Ida");
        ida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idaActionPerformed(evt);
            }
        });

        consultarVuelos.setText("Consultar Vuelos");
        consultarVuelos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                consultarVuelosMouseClicked(evt);
            }
        });
        consultarVuelos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultarVuelosActionPerformed(evt);
            }
        });

        solicitar.setText("Solicitar");
        solicitar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                solicitarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(127, 127, 127)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(regreso)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(idaVuelta))
                    .addComponent(jLabel2))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cmbDestino, 0, 106, Short.MAX_VALUE)
                            .addComponent(cmbOrigen, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(calendarioSalida, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(calendarioRegreso, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(ida)))
                .addGap(219, 219, 219))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(246, Short.MAX_VALUE)
                .addComponent(consultarVuelos)
                .addGap(165, 165, 165)
                .addComponent(solicitar)
                .addGap(41, 41, 41))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idaVuelta)
                    .addComponent(ida))
                .addGap(38, 38, 38)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(calendarioSalida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(calendarioRegreso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(regreso))
                .addGap(65, 65, 65)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(solicitar)
                    .addComponent(consultarVuelos))
                .addContainerGap(130, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Consultar Vuelos", jPanel2);

        jLabel5.setText("Si desea comprar el boleto previamente reservado");

        jLabel6.setText("Introduzca la Cedula de Identidad");

        comprarReserva.setText("Comprar");
        comprarReserva.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                comprarReservaMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(60, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(txtCedulaPagar, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(comprarReserva, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(73, 73, 73))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comprarReserva)
                    .addComponent(txtCedulaPagar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addContainerGap(276, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Pagar Reserva", jPanel3);

        jLabel9.setText("Introduzca la Cedula del Cliente");

        buscar_Modificar.setText("Buscar");
        buscar_Modificar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buscar_ModificarMouseClicked(evt);
            }
        });

        jLabel10.setText("Nombre");

        jLabel11.setText("Apellido");

        jLabel12.setText("Telefono");

        jLabel13.setText("Ciudad");

        jLabel14.setText("Estado");

        jLabel15.setText("Zona");

        modificarDatos.setText("Modificar");
        modificarDatos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                modificarDatosMouseClicked(evt);
            }
        });

        txtApellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApellidoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(jLabel9)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(133, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(46, 46, 46)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtZona, javax.swing.GroupLayout.DEFAULT_SIZE, 286, Short.MAX_VALUE)
                    .addComponent(txtEstado, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 286, Short.MAX_VALUE)
                    .addComponent(txtCiudad, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 286, Short.MAX_VALUE)
                    .addComponent(txtNombre, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 286, Short.MAX_VALUE)
                    .addComponent(txtApellido, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 286, Short.MAX_VALUE)
                    .addComponent(txtTelefono, javax.swing.GroupLayout.DEFAULT_SIZE, 286, Short.MAX_VALUE)
                    .addComponent(txtcedulaModificar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 286, Short.MAX_VALUE))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(modificarDatos)
                    .addComponent(buscar_Modificar))
                .addGap(23, 23, 23))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtcedulaModificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)
                            .addComponent(buscar_Modificar))
                        .addGap(48, 48, 48)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))
                        .addGap(56, 56, 56)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtZona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(247, 247, 247)
                        .addComponent(jLabel13))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(247, 247, 247)
                        .addComponent(txtCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(modificarDatos)
                .addGap(26, 26, 26))
        );

        jTabbedPane1.addTab("Modificar Datos Cliente", jPanel1);

        jLabel16.setText("Si desea Eliminar la Reserva de un Vuelo, por favor");

        Buscar_Eliminar.setText("Buscar");
        Buscar_Eliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Buscar_EliminarMouseClicked(evt);
            }
        });

        jLabel17.setText("Introduzca la Cedula de Identidad");

        jLabel18.setFont(new java.awt.Font("Verdana", 1, 11));
        jLabel18.setText("Datos del Vuelo Reservado________________________________________");

        jLabel7.setText("Origen");

        jLabel8.setText("Destino");

        jLabel19.setText("Fecha Salida");

        EliminarCompraVuelo.setText("Eliminar Reserva");
        EliminarCompraVuelo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EliminarCompraVueloMouseClicked(evt);
            }
        });

        jLabel21.setText("Fecha Regreso");

        jLabel22.setText("Numero de Vuelo");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addGap(18, 18, 18)
                        .addComponent(txtCedulaElim, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(Buscar_Eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 502, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel19)
                            .addComponent(jLabel22)
                            .addComponent(jLabel21))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtFechaSalidaVuelo, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtDestinoVuelo, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtOrigenVuelo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 223, Short.MAX_VALUE)
                            .addComponent(txtNumeroVuelo, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtFechaRegreso, javax.swing.GroupLayout.Alignment.LEADING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 168, Short.MAX_VALUE))
                    .addComponent(EliminarCompraVuelo, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap(72, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel16)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(txtCedulaElim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Buscar_Eliminar))
                .addGap(26, 26, 26)
                .addComponent(jLabel18)
                .addGap(28, 28, 28)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtOrigenVuelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtDestinoVuelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(txtFechaSalidaVuelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFechaRegreso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21))
                .addGap(21, 21, 21)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(EliminarCompraVuelo))
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtNumeroVuelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel22)))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Eliminar Reserva de un Vuelo", jPanel4);

        jLabel4.setFont(new java.awt.Font("Verdana", 1, 14));
        jLabel4.setForeground(new java.awt.Color(153, 0, 51));
        jLabel4.setText("Bienvenido al Sistema de Gestión de Clientes, Compra y Reserva de Boletos de AVENSA!");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 639, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel4)
                .addGap(34, 34, 34)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 448, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void solicitarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_solicitarMouseClicked
        // TODO add your handling code here:
        GUI2 ventana = new GUI2();
        ventana.setVisible(true);
}//GEN-LAST:event_solicitarMouseClicked

    private void consultarVuelosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultarVuelosActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_consultarVuelosActionPerformed

    private void consultarVuelosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_consultarVuelosMouseClicked
        // TODO add your handling code here:

        Vuelo datosVuelo = new Vuelo();
        String destino = (String) cmbDestino.getSelectedItem();

        Calendar c1 = Calendar.getInstance();
        c1= calendarioSalida.getCalendar();
        Date fecha = c1.getTime();
        SimpleDateFormat Formato = new SimpleDateFormat("dd/MM/yyyy");
        String fechaSalida = Formato.format(fecha);

        Calendar c2 = Calendar.getInstance();
        c1= calendarioRegreso.getCalendar();
        Date fecha2 = c2.getTime();
        SimpleDateFormat Formato2 = new SimpleDateFormat("dd/MM/yyyy");
        String fechaRegreso = Formato2.format(fecha2);

        datosVuelo.setDestino(destino);
        datosVuelo.setFechaSalida(fechaSalida);
//        datosVuelo.setFechaRegreso(fechaRegreso);

        ClienteConexion co = new ClienteConexion();
//        co.abrirConexion();
//        co.enviar(datosVuelo);
    }//GEN-LAST:event_consultarVuelosMouseClicked

    private void idaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idaActionPerformed
        // TODO add your handling code here:
        if (ida.isSelected()==true){
            regreso.setVisible(false);
            calendarioRegreso.setVisible(false);
        }
}//GEN-LAST:event_idaActionPerformed

    private void idaVueltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idaVueltaActionPerformed
        // TODO add your handling code here:

        if (idaVuelta.isSelected()==true){
            regreso.setVisible(true);
            calendarioRegreso.setVisible(true);
        }
}//GEN-LAST:event_idaVueltaActionPerformed

    private void buscar_ModificarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buscar_ModificarMouseClicked
        // TODO add your handling code here:
        int peticion =2;

        Persona persona = new Persona();
        String cedulaModificar = txtcedulaModificar.getText();
        persona.setCedula(cedulaModificar);

        Vector datosPeticion = new Vector();
        datosPeticion.add(0, peticion);
        datosPeticion.add(1, persona);

        ClienteConexion conexion = new ClienteConexion();
        conexion.abrirConexion();
        conexion.enviar(datosPeticion);

        respuesta = (Vector) conexion.recibir();

        Persona personaRecibida = new Persona();
        personaRecibida = (Persona)respuesta.elementAt(0);

        if (personaRecibida.getNombre() == null) 
            JOptionPane.showMessageDialog(this, "El Usuario No se Encuentra Registrado en el Sistema" );

        else
        {

            System.out.println("Persona Recibida: "+personaRecibida.getNombre());

            txtNombre.setText(personaRecibida.getNombre());
            txtApellido.setText(personaRecibida.getApellido());
            txtTelefono.setText(personaRecibida.getTelefono());
            txtCiudad.setText(personaRecibida.getCiudad());
            txtEstado.setText(personaRecibida.getEstado());
            txtZona.setText(personaRecibida.getZona());
        }
    }//GEN-LAST:event_buscar_ModificarMouseClicked

    private void modificarDatosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_modificarDatosMouseClicked
        // TODO add your handling code here:
        int peticion =3;

        Persona persona = new Persona();
        
        persona.setNombre(txtNombre.getText());
        persona.setApellido(txtApellido.getText());
        persona.setTelefono(txtTelefono.getText());
        persona.setCiudad(txtCiudad.getText());
        persona.setEstado(txtEstado.getText());
        persona.setZona(txtZona.getText());
        persona.setCedula(txtcedulaModificar.getText());

        Vector datosPeticion = new Vector();
        datosPeticion.add(0, peticion);
        datosPeticion.add(1, persona);

        ClienteConexion conexion = new ClienteConexion();
        conexion.abrirConexion();
        conexion.enviar(datosPeticion);

        JOptionPane.showMessageDialog(this, "Se han guardado los cambios!" );


    }//GEN-LAST:event_modificarDatosMouseClicked

    private void txtApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApellidoActionPerformed

    private void Buscar_EliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Buscar_EliminarMouseClicked
        // TODO add your handling code here:

        int peticion = 4;
        Persona persona = new Persona();

        persona.setCedula(txtCedulaElim.getText());

        Vector datosPeticion = new Vector();
        datosPeticion.add(0, peticion);
        datosPeticion.add(1, persona);

        ClienteConexion conexion = new ClienteConexion();
        conexion.abrirConexion();
        conexion.enviar(datosPeticion);

        respuesta = (Vector) conexion.recibir();
        System.out.println("recibio");

        Vuelo vueloRecibido = new Vuelo();
        try{
        vueloRecibido = (Vuelo) respuesta.elementAt(0);
        }
        catch(Exception e){
        System.out.println("cae en el cath");
        }
        System.out.println("vuelo recibido = " + vueloRecibido.getIdVuelo());
        String destino = (String)respuesta.elementAt(1);
        String origen = (String)respuesta.elementAt(2);

        if (vueloRecibido.getIdVuelo() == null)
            JOptionPane.showMessageDialog(this, "El Usuario No tiene un Vuelo asignado" );

        else
        {

            System.out.println("Vuelo Recibido: "+vueloRecibido.getIdVuelo());

            txtOrigenVuelo.setText(origen);
            txtDestinoVuelo.setText(destino);
            txtFechaSalidaVuelo.setText(vueloRecibido.getFechaSalida());
            txtFechaRegreso.setText(vueloRecibido.getFechaRegreso());
            txtNumeroVuelo.setText(vueloRecibido.getIdVuelo());
        }

        
    }//GEN-LAST:event_Buscar_EliminarMouseClicked

    private void comprarReservaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_comprarReservaMouseClicked
        // TODO add your handling code here:
        Persona persona = new Persona();

        persona.setCedula(txtCedulaPagar.getText());

        ClienteConexion conexion = new ClienteConexion();
//       conexion.abrirConexion();
//       conexion.enviar(datosVuelo);

    }//GEN-LAST:event_comprarReservaMouseClicked

    private void EliminarCompraVueloMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EliminarCompraVueloMouseClicked
        // TODO add your handling code here:
        int peticion =5;

        Vuelo datosVuelo = new Vuelo();
        Persona persona = new Persona();

        persona.setCedula(txtCedulaElim.getText());
        datosVuelo.setIdVuelo(txtNumeroVuelo.getText());

        Vector datosPeticion = new Vector();
        datosPeticion.add(0, peticion);
        datosPeticion.add(1, datosVuelo);
        datosPeticion.add(2, persona);
        
        ClienteConexion conexion = new ClienteConexion();
        conexion.abrirConexion();
        conexion.enviar(datosPeticion);

        JOptionPane.showMessageDialog(this, "La Reserva ha sido eliminada!" );

    }//GEN-LAST:event_EliminarCompraVueloMouseClicked

    private void cmbOrigenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbOrigenActionPerformed
        // TODO add your handling code here:
        int peticion =6;
        String origen=cmbOrigen.getSelectedItem().toString();
        System.out.println("origen = " + origen);

        Vuelo vuelo = new Vuelo();
        vuelo.setDestino(origen);

    }//GEN-LAST:event_cmbOrigenActionPerformed



    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Buscar_Eliminar;
    private javax.swing.JButton EliminarCompraVuelo;
    private javax.swing.JButton buscar_Modificar;
    private javax.swing.ButtonGroup buttonGroup1;
    private org.freixas.jcalendar.JCalendarCombo calendarioRegreso;
    private org.freixas.jcalendar.JCalendarCombo calendarioSalida;
    private javax.swing.JComboBox cmbDestino;
    private javax.swing.JComboBox cmbOrigen;
    private javax.swing.JButton comprarReserva;
    private javax.swing.JButton consultarVuelos;
    private javax.swing.JRadioButton ida;
    private javax.swing.JRadioButton idaVuelta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JButton modificarDatos;
    private javax.swing.JLabel regreso;
    private javax.swing.JButton solicitar;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtCedulaElim;
    private javax.swing.JTextField txtCedulaPagar;
    private javax.swing.JTextField txtCiudad;
    private javax.swing.JTextField txtDestinoVuelo;
    private javax.swing.JTextField txtEstado;
    private javax.swing.JTextField txtFechaRegreso;
    private javax.swing.JTextField txtFechaSalidaVuelo;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNumeroVuelo;
    private javax.swing.JTextField txtOrigenVuelo;
    private javax.swing.JTextField txtTelefono;
    private javax.swing.JTextField txtZona;
    private javax.swing.JTextField txtcedulaModificar;
    // End of variables declaration//GEN-END:variables

}
